export const LOGIN_USER_START = "LOGIN_USER_START";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const REGISTER_TENANT_START="REGISTER_TENANT_START";
export const REGISTER_TENANT_SUCCESS="REGISTER_TENANT_SUCCESS";
export const REGISTER_TENANT_FAILURE="REGISTER_TENANT_FAILURE";

export const REGISTER_USER_START="REGISTER_USER_START";
export const REGISTER_USER_SUCCESS="REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE="REGISTER_USER_FAILURE";

export const LOGIN_TENANT_START="LOGIN_TENANT_START";
export const LOGIN_TENANT_SUCCESS="LOGIN_TENANT_SUCCESS";
export const LOGIN_TENANT_FAILURE="LOGIN_TENANT_FAILURE";

export const VALIDATE_TOKEN_START="VALIDATE_TOKEN_START";
export const VALIDATE_TOKEN_SUCCESS="VALIDATE_TOKEN_SUCCESS";
export const VALIDATE_TOKEN_FAILURE="VALIDATE_TOKEN_FAILURE";

export const GETUSERSBY_TENANT_START="GETUSERSBY_TENANT_START";
export const GETUSERSBY_TENANT_SUCCESS="GETUSERSBY_TENANT_SUCCESS";
export const GETUSERSBY_TENANT_FAILURE="GETUSERSBY_TENANT_FAILURE";

export const GET_PROFILE_BYUSERID_START="GET_PROFILE_BYUSERID_START";
export const GET_PROFILE_BYUSERID_SUCCESS="GET_PROFILE_BYUSERID_SUCCESS";
export const GET_PROFILE_BYUSERID_FAILURE="GET_PROFILE_BYUSERID_FAILURE";

export const GET_PROFILE_START="GET_PROFILE_START";
export const GET_PROFILE_SUCCESS="GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILURE="GET_PROFILE_FAILURE";