export const SEND_EMAIL_START="SEND_EMAIL_START";
export const SEND_EMAIL_SUCCESS="SEND_EMAIL_SUCCESS";
export const SEND_EMAIL_FAILURE="SEND_EMAIL_FAILURE";

export const GET_INBOX_BYUSERID_START="GET_INBOX_BYUSERID_START";
export const GET_INBOX_BYUSERID_SUCCESS="GET_INBOX_BYUSERID_SUCCESS";
export const GET_INBOX_BYUSERID_FAILURE="GET_INBOX_BYUSERID_FAILURE";

export const GET_SENT_BYUSERID_START="GET_SENT_BYUSERID_START";
export const GET_SENT_BYUSERID_SUCCESS="GET_SENT_BYUSERID_SUCCESS";
export const GET_SENT_BYUSERID_FAILURE="GET_SENT_BYUSERID_FAILURE";

export const GET_THREAD_BYID_START="GET_THREAD_BYID_START";
export const GET_THREAD_BYID_SUCCESS="GET_THREAD_BYID_SUCCESS";
export const GET_THREAD_BYID_FAILURE="GET_THREAD_BYID_FAILURE";

export const REPLY_TO_EMAIL_BY_EMAILID_START="REPLY_TO_EMAIL_BY_EMAILID_START";
export const REPLY_TO_EMAIL_BY_EMAILID_SUCCESS="REPLY_TO_EMAIL_BY_EMAILID_SUCCESS";
export const REPLY_TO_EMAIL_BY_EMAILID_FAILURE="REPLY_TO_EMAIL_BY_EMAILID_FAILURE";

export const DELETE_EMAIL_START="DELETE_EMAIL_START";
export const DELETE_EMAIL_SUCCESS="DELETE_EMAIL_SUCCESS";
export const DELETE_EMAIL_FAILURE="DELETE_EMAIL_FAILURE";

export const ARCHIEVE_EMAIL_START="ARCHIEVE_EMAIL_START";
export const ARCHIEVE_EMAIL_SUCCESS="ARCHIEVE_EMAIL_SUCCESS";
export const ARCHIEVE_EMAIL_FAILURE="ARCHIEVE_EMAIL_FAILURE";

export const UNSUBSCRIBE_SENDER_START="UNSUBSCRIBE_SENDER_START";
export const UNSUBSCRIBE_SENDER_SUCCESS="UNSUBSCRIBE_SENDER_SUCCESS";
export const UNSUBSCRIBE_SENDER_FAILURE="UNSUBSCRIBE_SENDER_FAILURE";