export const CREATE_MEETING_START="CREATE_MEETING_START";
export const CREATE_MEETING_SUCCESS="CREATE_MEETING_SUCCESS";
export const CREATE_MEETING_FAILURE="CREATE_MEETING_FAILURE";

export const GETMEETING_LIST_BYTENANT_START="GETMEETING_LIST_BYTENANT_START";
export const GETMEETING_LIST_BYTENANT_SUCCESS="GETMEETING_LIST_BYTENANT_SUCCESS";
export const GETMEETING_LIST_BYTENANT_FAILURE="GETMEETING_LIST_BYTENANT_FAILURE";

export const GETMEETING_BYID_START="GETMEETING_BYID_START";
export const GETMEETING_BYID_SUCCESS="GETMEETING_BYID_SUCCESS";
export const GETMEETING_BYID_FAILURE="GETMEETING_BYID_FAILURE";

export const JOIN_MEETING_START="JOIN_MEETING_START";
export const JOIN_MEETING_SUCCESS="JOIN_MEETING_SUCCESS";
export const JOIN_MEETING_FAILURE="JOIN_MEETING_FAILURE";

export const TOGGLE_RECORDING_START="TOGGLE_RECORDING_START";
export const TOGGLE_RECORDING_SUCCESS="TOGGLE_RECORDING_SUCCESS";
export const TOGGLE_RECORDING_FAILURE="TOGGLE_RECORDING_FAILURE";

export const SENDCHAT_INMEETING_START="SENDCHAT_INMEETING_START";
export const SENDCHAT_INMEETING_SUCCESS="SENDCHAT_INMEETING_SUCCESS";
export const SENDCHAT_INMEETING_FAILURE="SENDCHAT_INMEETING_FAILURE";

export const GET_SUMMARY_START="GET_SUMMARY_START";
export const GET_SUMMARY_SUCCESS="GET_SUMMARY_SUCCESS";
export const GET_SUMMARY_FAILURE="GET_SUMMARY_FAILURE";

export const GET_ATTENDANCE_START="GET_ATTENDANCE_START";
export const GET_ATTENDANCE_SUCCESS="GET_ATTENDANCE_SUCCESS";
export const GET_ATTENDANCE_FAILURE="GET_ATTENDANCE_FAILURE";