export const CREATE_CHANNEL_START="CREATE_CHANNEL_START";
export const CREATE_CHANNEL_SUCCESS="CREATE_CHANNEL_SUCCESS";
export const CREATE_CHANNEL_FAILURE="CREATE_CHANNEL_FAILURE";

export const GET_CHANNELS_BYTENANTID_START="GET_CHANNELS_BYTENANTID_START";
export const GET_CHANNELS_BYTENANTID_SUCCESS="GET_CHANNELS_BYTENANTID_SUCCESS";
export const GET_CHANNELS_BYTENANTID_FAILURE="GET_CHANNELS_BYTENANTID_FAILURE";

export const SEND_MESSAGE_START="SEND_MESSAGE_START";
export const SEND_MESSAGE_SUCCESS="SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAILURE="SEND_MESSAGE_FAILURE";

export const GETTHREAD_BYMESSAGEID_START="GETTHREAD_BYMESSAGEID_START";
export const GETTHREAD_BYMESSAGEID_SUCCESS="GETTHREAD_BYMESSAGEID_SUCCESS";
export const GETTHREAD_BYMESSAGEID_FAILURE="GETTHREAD_BYMESSAGEID_FAILURE";

export const REPLY_TO_MESSAGE_START="REPLY_TO_MESSAGE_START";
export const REPLY_TO_MESSAGE_SUCCESS="REPLY_TO_MESSAGE_SUCCESS";
export const REPLY_TO_MESSAGE_FAILURE="REPLY_TO_MESSAGE_FAILURE";

export const REACT_TO_MESSAGE_START="REACT_TO_MESSAGE_START";
export const REACT_TO_MESSAGE_SUCCESS="REACT_TO_MESSAGE_SUCCESS";
export const REACT_TO_MESSAGE_FAILURE="REACT_TO_MESSAGE_FAILURE";

export const GETUSER_PRESENCE_BYUSERID_START="GETUSER_PRESENCE_BYUSERID_START";
export const GETUSER_PRESENCE_BYUSERID_SUCCESS="GETUSER_PRESENCE_BYUSERID_SUCCESS";
export const GETUSER_PRESENCE_BYUSERID_FAILURE="GETUSER_PRESENCE_BYUSERID_FAILURE";

export const PINMESSAGE_BYMESSAGEID_START="PINMESSAGE_BYMESSAGEID_START";
export const PINMESSAGE_BYMESSAGEID_SUCCESS="PINMESSAGE_BYMESSAGEID_SUCCESS";
export const PINMESSAGE_BYMESSAGEID_FAILURE="PINMESSAGE_BYMESSAGEID_FAILURE";

export const DELETE_MESSAGE_BYMESSAGEID_START="DELETE_MESSAGE_BYMESSAGEID_START";
export const DELETE_MESSAGE_BYMESSAGEID_SUCCESS="DELETE_MESSAGE_BYMESSAGEID_SUCCESS";
export const DELETE_MESSAGE_BYMESSAGEID_FAILURE="DELETE_MESSAGE_BYMESSAGEID_FAILURE";