export const GET_ALLPLANS_START="GET_ALLPLANS_START";
export const GET_ALLPLANS_SUCCESS="GET_ALLPLANS_SUCCESS";
export const GET_ALLPLANS_FAILURE="GET_ALLPLANS_FAILURE";

export const GET_TENANT_PLAN_START="GET_TENANT_PLAN_START";
export const GET_TENANT_PLAN_SUCCESS="GET_TENANT_PLAN_SUCCESS";
export const GET_TENANT_PLAN_FAILURE="GET_TENANT_PLAN_FAILURE";

export const ASSIGN_PLAN_TO_TENANT_START="ASSIGN_PLAN_TO_TENANT_START";
export const ASSIGN_PLAN_TO_TENANT_SUCCESS="ASSIGN_PLAN_TO_TENANT_SUCCESS";
export const ASSIGN_PLAN_TO_TENANT_FAILURE="ASSIGN_PLAN_TO_TENANT_FAILURE";

export const GET_TENANT_MODULES_START="GET_TENANT_MODULES_START";
export const GET_TENANT_MODULES_SUCCESS="GET_TENANT_MODULES_SUCCESS";
export const GET_TENANT_MODULES_FAILURE="GET_TENANT_MODULES_FAILURE";