export const CREATE_BOARD_START="CREATE_BOARD_START";
export const CREATE_BOARD_SUCCESS="CREATE_BOARD_SUCCESS";
export const CREATE_BOARD_FAILURE="CREATE_BOARD_FAILURE";

export const GET_BOARDS_START="GET_BOARDS_START";
export const GET_BOARDS_SUCCESS="GET_BOARDS_SUCCESS";
export const GET_BOARDS_FAILURE="GET_BOARDS_FAILURE";

export const CREATE_TICKETS_START="CREATE_TICKETS_START";
export const CREATE_TICKETS_SUCCESS="CREATE_TICKETS_SUCCESS";
export const CREATE_TICKETS_FAILURE="CREATE_TICKETS_FAILURE";

export const GET_TICKETS_BYBOARDID_START="GET_TICKETS_BYBOARDID_START";
export const GET_TICKETS_BYBOARDID_SUCCESS="GET_TICKETS_BYBOARDID_SUCCESS";
export const GET_TICKETS_BYBOARDID_FAILURE="GET_TICKETS_BYBOARDID_FAILURE";

export const UPDATE_TICKET_BYTICKETID_START="UPDATE_TICKET_BYTICKETID_START";
export const UPDATE_TICKET_BYTICKETID_SUCCESS="UPDATE_TICKET_BYTICKETID_SUCCESS";
export const UPDATE_TICKET_BYTICKETID_FAILURE="UPDATE_TICKET_BYTICKETID_FAILURE";

export const GET_TICKET_DETAILS_BYTICKETID_START="GET_TICKET_DETAILS_BYTICKETID_START";
export const GET_TICKET_DETAILS_BYTICKETID_SUCCESS="GET_TICKET_DETAILS_BYTICKETID_SUCCESS";
export const GET_TICKET_DETAILS_BYTICKETID_FAILURE="GET_TICKET_DETAILS_BYTICKETID_FAILURE";

export const ADD_COMMENT_TO_TICKET_BYID_START="ADD_COMMENT_TO_TICKET_BYID_START";
export const ADD_COMMENT_TO_TICKET_BYID_SUCCESS="ADD_COMMENT_TO_TICKET_BYID_SUCCESS";
export const ADD_COMMENT_TO_TICKET_BYID_FAILURE="ADD_COMMENT_TO_TICKET_BYID_FAILURE";

export const GETCOMMENTS_BYTICKETID_START="GETCOMMENTS_BYTICKETID_START";
export const GETCOMMENTS_BYTICKETID_SUCCESS="GETCOMMENTS_BYTICKETID_SUCCESS";
export const GETCOMMENTS_BYTICKETID_FAILURE="GETCOMMENTS_BYTICKETID_FAILURE";

export const GETREPORT_BYBOARDID_START="GETREPORT_BYBOARDID_START";
export const GETREPORT_BYBOARDID_SUCCESS="GETREPORT_BYBOARDID_SUCCESS";
export const GETREPORT_BYBOARDID_FAILURE="GETREPORT_BYBOARDID_FAILURE";

export const GETSPRINT_BYBOARDID_START="GETSPRINT_BYBOARDID_START";
export const GETSPRINT_BYBOARDID_SUCCESS="GETSPRINT_BYBOARDID_SUCCESS";
export const GETSPRINT_BYBOARDID_FAILURE="GETSPRINT_BYBOARDID_FAILURE";