export const GET_TICKET_DETAILS_BYTICKETID_START =
  "GET_TICKET_DETAILS_BYTICKETID_START";
export const GET_TICKET_DETAILS_BYTICKETID_SUCCESS =
  "GET_TICKET_DETAILS_BYTICKETID_SUCCESS";
export const GET_TICKET_DETAILS_BYTICKETID_FAILURE =
  "GET_TICKET_DETAILS_BYTICKETID_FAILURE";
