export const SEARCH_USERS_START="SEARCH_USERS_START";
export const SEARCH_USERS_SUCCESS="SEARCH_USERS_SUCCESS";
export const SEARCH_USERS_FAILURE="SEARCH_USERS_FAILURE";


export const DOWNLOAD_FILE_START="DOWNLOAD_FILE_START";
export const DOWNLOAD_FILE_SUCCESS="DOWNLOAD_FILE_SUCCESS";
export const DOWNLOAD_FILE_FAILURE="DOWNLOAD_FILE_FAILURE";

export const UPLOAD_FILE_START="UPLOAD_FILE_START";
export const UPLOAD_FILE_SUCCESS="UPLOAD_FILE_SUCCESS";
export const UPLOAD_FILE_FAILURE="UPLOAD_FILE_FAILURE";